
infra:
  image: distribot/infra:latest
  environment:
    - TERM=xterm
    - RABBITMQ_USERNAME=distribot
    - RABBITMQ_PASSWORD=distribot
  working_dir: /var/www/distribot
  command: bash -c "./provision/infra.sh && tail -f /dev/null"
  ports:
    - 5672
    - 15672
    - 6379
    - 443

code:
  build: .
  dockerfile: ./Dockerfile
  volumes:
    - ./:/var/www/distribot-ui
  environment:
    - TERM=xterm
    - INFRA_HOST=infra_1
    - RABBITMQ_USERNAME=distribot
    - RABBITMQ_PASSWORD=distribot
  working_dir: /var/www/distribot-ui
  links:
    - infra
  ports:
    - 3000
    - 9292
  command: bash -c "./provision/distribot-ui.sh && tail -f /dev/null"
