# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dde7f940256696d2804eb4498a3f101f3e8611c8b9ee978ee9b587621daa60cc019ed3e5e0e0bf4ea874eb01e4dd321d64df0e8dd88ac03347a283b7e53d2976

test:
  secret_key_base: e08cd2dc81b993959853ae685d73f08f78a978dffb1063c65b9d8cd4201ce79d5f87fe642dd7d9c3b28a577891e22bb2953cfddb98e95356aa7289106ba863a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
